on:
  workflow_call:

jobs:
  container-release:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:

      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          path: PandABlocks-rootfs

      - name: Checkout rootfs builder
        uses: actions/checkout@v2
        with:
          repository: dls-controls/rootfs
          path: rootfs

      - name: Checkout annotypes
        uses: actions/checkout@v2
        with:
          repository: dls-controls/annotypes
          path: annotypes

      - name: Checkout pymalcolm
        uses: actions/checkout@v2
        with:
          repository: dls-controls/pymalcolm
          path: pymalcolm

      - name: Checkout malcolmjs
        uses: actions/checkout@v2
        with:
          repository: dls-controls/malcolmjs
          path: malcolmjs

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: shihab-dls/pandablocks-container
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Rebuild and release image
        uses: docker/build-push-action@v2
        with:
          context: . 
          file: ./PandABlocks-rootfs/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          push: ${{ github.event_name != 'pull_request' }}
