name: CI

on:
  push:
  pull_request:

jobs:

  conainer-release:
    uses: ./.github/workflows/_container-release.yml
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    
